### mxnet-ndarray test

In [1]:
from mxnet import ndarray as nd

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL


In [2]:
nd.ones((3, 4))


[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
<NDArray 3x4 @cpu(0)>

In [7]:
a = nd.array([1, 2, 3]).reshape((3,1))
a


[[ 1.]
 [ 2.]
 [ 3.]]
<NDArray 3x1 @cpu(0)>

In [8]:
b = nd.arange(2).reshape((1,2))
b


[[ 0.  1.]]
<NDArray 1x2 @cpu(0)>

In [ ]:
a + 